### PR TITLE
Wrap route

### PR DESCRIPTION
**Pull request by mrhut10**
I've removed the ParallaxProvider from the page elements and instead wrapped the whole gatsby app with it.

was hoping you could see if fix's the problem without the need of the update method. however do have some interesting information regarding the methods avaliable for you which i'll screenshot below.

ok when i render the stringify of the parallaxController object (see code below)
```js
  const IndexPage = ({ data, parallaxController }) => {
    return JSON.stringify(parallaxController);
  }
  IndexPage.propTypes = {
    data: PropTypes.object,
    parallaxController: PropTypes.object,
  };
  export default withController(IndexPage);
```
i appear to get a empty object, however you'll notice that on the react-tools all the expected methods/properties are there. (see screenshot) so thats interesting, mmmm.

when you where saying it was null, how/where where you checking this?

paralax

p.s. if we still need the update method you want, we might need to detect the router updating its state.

### CODE REVIEW

**Comment by lukebennett88** [comment]
Hey @mrhut10 
Thanks again for taking the time to look at this for me.
Unfortunately this still has fixed my issue, here is a video showing the issue I'm having using the deploy preview: <https://gfycat.com/personalactivedarwinsfox>

If we can get the `update()` method to work, I'm pretty sure it will fix this issue, and using the `exports.wrapRootElement` function in `gatsby-browser.js` feels like the right thing to do here. I think we're close.

The code I was using to get the `parallaxController.update()` method to return null was in my original issue:

```jsx
import React from 'react';
import { graphql } from 'gatsby';
import { ParallaxProvider, withController } from 'react-scroll-parallax';
import PropTypes from 'prop-types';

const IndexPage = props => {
  console.log(props);
  return (
    <ParallaxProvider>
      ...rest of page
    </ParallaxProvider>
  );
};

IndexPage.propTypes = {
  data: PropTypes.object,
};
```

**Comment by lukebennett88** [comment]
A really simple fix would be to use `<a>` instead of `<Link>` in the navigation.
I'd rather not go that route, but I even tried running:

```js
setTimeout(() => {
  parallaxController.update();
}, 500);
```
and it still didn't work...
Looks like @jscottsmith (who created the package) has seen this issue before and was unable to fix it (https://github.com/jscottsmith/react-scroll-parallax/issues/65).

**Comment by mrhut10** [comment]
oh interesting i get the error of null now,
its a build time error not a runtime error.

ok, well firstly assuming is running
OK I've wrapped each of the pages i think that needed it in a wrapper which adds the hook to update the parallax controller.

the hook has been tested and is running the provided function, however the visual UI problem is hard to diagnose on my end as not 100% that the problem is still happening for me (Firefox)



the build time error i'll play with and try to fix now.

**Comment by mrhut10** [comment]
ok i believe fixed the build time error, sorry i hadn't seen as had only used in develop mode locally.
and had assumed was a runtime error.

**Comment by mrhut10** [comment]
yay all building now, look forward to feedback :) @lukebennett88

**Comment by lukebennett88** [comment]
Thanks so much @mrhut10 this is working for me when I scroll down the `index` page and switch to the `contact` page, but not when I scroll the `index` page and switch to the `why page`.

When I look at those 2 pages, the difference I can see 2 main differences; 
- The contact page calls `parallaxController.update()` inside of `useEffect`
- The `ContactPage` function is passed into the `withController` which is the default export

I wouldn't have thought either of these things were necessary with the `ParallaxUpdate` component, as it does both these things, so I'm still not sure how to fix this.

The `index` page is also showing the parallax images incorrectly if I scroll the `contact` or `why` pages and switch back to the `index` page.

**Comment by lukebennett88** [comment]
@mrhut10 
I've temporarily removed the Parallax effect as it was still a bit janky.
Do you think we might have more luck with [react-spring?](https://www.react-spring.io/docs/props/parallax)

**Comment by mrhut10** [comment]
@lukebennett88 sorry I've been out of it, solar part of week over :)
hard for me to diagnose a UI as I'm not always certain what is your expected behavior.

i've heard of react spring and seen a few people running courses on it, so sounds interesting.
did you end up having an attempt at using it? I'll have a look to see if you've included it i guess.

talk when your awake :)

**Comment by lukebennett88** [comment]
@mrhut I've had a look at react-spring, I'm having a hard time with it as well.
Using the old render-props API there was a `<Parallax>` component for doing exactly what I'm trying to do, but I was having a lot of trouble getting it to play nicely with `gatsby-image` I think the size of the image was collapsing due to being absolutely positioned. It also looks like it was designed for animations that were 100vh at a time which I didn't want to do (the images should be full width, and however tall they should be at that aspect ratio).
The newer hooks based API might be more flexible.
I found this demo which is close to what I want: <https://codesandbox.io/embed/py912w5k6m>
I then pulled out everything but the essentials: <https://codesandbox.io/s/scroll-animation-with-react-spring-iqwzt>
I've tried to use that in my repo, but it doesn't seem to be working.

**Pull request merged**
